### ISSUE TITLE
Kfdef is still required by odh-dashboard when new operator is in use.

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-operator#288]
**Describe the bug**
When testing new operator rework image [dev-0.0.1](https://github.com/opendatahub-io/opendatahub-operator/releases/tag/v0.0.1), found error logs flooding from odh-dashboard pod, see below:

**Expected behavior**
Should not see such error

**Screenshots**
```
{"level":30,"time":1688972061064,"pid":17,"hostname":"odh-dashboard-58fb784664-6kldl","reqId":"req-1v8","res":{"statusCode":200},"responseTime":0.31173789501190186,"msg":"request completed"}
{"level":50,"time":1688972064878,"pid":17,"hostname":"odh-dashboard-58fb784664-6kldl","err":{"type":"HttpError","message":"HTTP request failed","stack":"HttpError: HTTP request failed\n    at Request._callback (/usr/src/app/backend/node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js:1482:40)\n    at self.callback (/usr/src/app/backend/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:513:28)\n    at Request.<anonymous> (/usr/src/app/backend/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:513:28)\n    at IncomingMessage.<anonymous> (/usr/src/app/backend/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:627:28)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","response":{"statusCode":404,"body":"404 page not found\n","headers":{"audit-id":"a3a0b514-06d7-4a89-91de-be18fc4d5ab6","cache-control":"no-cache, private","content-type":"text/plain; charset=utf-8","x-content-type-options":"nosniff","x-kubernetes-pf-flowschema-uid":"9546f919-28af-439f-9c13-33af617d0837","x-kubernetes-pf-prioritylevel-uid":"2e3787dd-b27b-40ae-8d1f-464021030194","date":"Mon, 10 Jul 2023 06:54:24 GMT","content-length":"19","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"172.30.0.1:443","port":"443","hostname":"172.30.0.1","hash":null,"search":null,"query":null,"pathname":"/apis/kfdef.apps.kubeflow.org/v1/namespaces/opendatahub/kfdefs","path":"/apis/kfdef.apps.kubeflow.org/v1/namespaces/opendatahub/kfdefs","href":"https://172.30.0.1:443/apis/kfdef.apps.kubeflow.org/v1/namespaces/opendatahub/kfdefs"},"method":"GET","headers":{"Accept":"application/json","Authorization":"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlQ5RXNsTDhhN3UyLVlEMW1Rb21ESXB0UXdVRmpEOTRDVjZmR0VMZjZUdWsifQ.eyJhdWQiOlsiaHR0cHM6Ly9yaC1vaWRjLnMzLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tLzIzYzczNHN0M3BuN2wxNjdtcTk3ZDBvdDg4NDhsZ3JsIl0sImV4cCI6MTcyMDUwNTUzNCwiaWF0IjoxNjg4OTY5NTM0LCJpc3MiOiJodHRwczovL3JoLW9pZGMuczMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMjNjNzM0c3QzcG43bDE2N21xOTdkMG90ODg0OGxncmwiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6Im9wZW5kYXRhaHViIiwicG9kIjp7Im5hbWUiOiJvZGgtZGFzaGJvYXJkLTU4ZmI3ODQ2NjQtNmtsZGwiLCJ1aWQiOiJjNWE3N2RkOC00OTZiLTRiN2MtOGU4MS1kZTdhNzk5MTFhOGMifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6Im9kaC1kYXNoYm9hcmQiLCJ1aWQiOiJlNTg4YjJlNy1lNjZhLTQ2M2ItYjMzYS0zMmVmMDQ3YjU1ZjkifSwid2FybmFmdGVyIjoxNjg4OTczMTQxfSwibmJmIjoxNjg4OTY5NTM0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6b3BlbmRhdGFodWI6b2RoLWRhc2hib2FyZCJ9.nkfxD5XfNxIKX5B7h5jRFkWTNJWxj7k8pz4iDqAFroim-sdVMSGpUKmvkKveZrmSRirXvgAOlBH65ELh1LnGaKCYOBaP-D-IKX1RP4usx7dF2ZLs4gsL6zW-2Mz1S7zX1i9fzAzGzaAN61dgcfZ6i0E3ZL2jj3VeRwi077GKqA1bzueKgehcK--fRoK7xIIDL9ZwO9HDQWMXTia_8PnZTzPTFKbL3H9xO6gYrUnHJggwybs_lqpzZag7nfhIS37JBFW8a3ID-QoXolyXCshl94I2Gv607H0J-QqdDtMxYXDNn0Y8ocqY47wtLv8qZIaY0ZLK9MXGi11yOy93Qh51kpqCbQxIjudCVdsAVogCOL0fbGD9umY8pcch3gmrq8WWG7DZLVcxEEFbCEBKXV-g69QQcoYnwHMPIbnfR90Vhm1eNlXUfwFTjdmTByLGZ895oduvQkyna6XkKmatOVtDiaN9HbNDTemdoeLYGfZ3i3ypz0qCuG98RBW4cFKu5sp_bm5BRcTZ8x4f2xwOtDZ76oOQyWsPVuFOGm3QN7qazbsxo2UH9ywJEPiFWCGaGf6IPzcXbWr14ReQM8rzDi8pM39uLNvWvo8Wx2fGOPe_Z9lr4heKysXmqk7nzZPOPZqTcZQnFMlA0RIoPR53Xqtix56oNzbzM2l00N9qBqNHMbI"}}},"body":"404 page not found\n","statusCode":404,"name":"HttpError"},"msg":"failed to get kfdefs"}
{"level":30,"time":1688972064899,"pid":17,"hostname":"odh-dashboard-58fb784664-6kldl","msg":"Pipelines feature enabled, computing operator state..."}
{"level":30,"time":1688972064914,"pid":17,"hostname":"odh-dashboard-58fb784664-6kldl","msg":"Pipeline Operator status: false"}
```

**Additional context**
Related to issue in odh-dashboard https://github.com/opendatahub-io/odh-dashboard/issues/1491
temp. workaround https://github.com/opendatahub-io/opendatahub-operator/pull/286

**Comment by zdtsw** [comment]
close it as we do not need kfdef for operator v2.X any more
